### ISSUE TITLE
지역에 따른 국회의원 디비 구축하기

### ISSUE THREAD

**Issue by hoony-o-1** [codeforseoul/congress-report-web#12]

**Comment by jeff-lim** [comment]
선거구-의원 매칭 http://www.assembly.go.kr/renew10/mem/mem/mem_search.jsp

**Comment by yejiyun** [comment]
SQL테이블에서 메일러 모듈로 데이터를 전달하는 모듈은 다 구현했어요.
![db](https://cloud.githubusercontent.com/assets/13119300/8649612/e9cd27ba-29a6-11e5-83f0-9035e3510739.png)
행정동-의원명 매칭에 필요한 데이터는 첨부한 이미지와 같이 테이블을 구성해주시면 좋을거 같아요.
DB는 MySQL로 구성되면 편할 것 같아요

**Comment by hoony-o-1** [comment]
제가 예지님 속도를 못따라가서 죄송해요 ㅜㅜ form 데이터 넘겨주는 부분은 내일 중으로 만들어드릴게요, 혹시 폼데이터로 사용자가 어떤 부분을 선택해서 넘겨드리면 되는지 확인해주실래요? 이 부분은 욱재님께서 진행하기 힘드시면 제가 진행해서 sql export 해서 드릴게요 우선 :) :+1:

**Comment by mozodev** [comment]
선거구-의원 매칭 http://www.assembly.go.kr/renew10/mem/mem/mem_search.jsp
클릭했더니
![2015-08-08 3 08 12](https://cloud.githubusercontent.com/assets/1661950/9149447/586b7620-3de5-11e5-9bc6-b803cd1ee15a.png)
브라우저도 우리나라 국회를 유해 콘텐츠라 생각하는건가 ㅋㅋㅋㅋㅋ

**Comment by hoony-o-1** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
