### ISSUE TITLE
원하는 데이터를 포퐁API에서 불러와서 조립하기(mandrill)로 보내기 위한

### ISSUE THREAD

**Issue by hoony-o-1** [codeforseoul/congress-report-web#13]

**Comment by jeff-lim** [comment]
실제로 프로젝트가 들어가면, 
mandrill에서 참조하는 데이터는 외부DB(eg.포퐁)가 아니라 내부DB가 되어야함.

**Comment by hoony-o-1** [comment]
@soyoungpark 어차피 메일링이기 때문에 실시간으로 속도가 중요한 이슈가 아니라 따로 내부 디비는 구축하지 않아도 되구요 후에 2.0 이후 버전에서 자체적으로 크롤한 데이터와 포퐁데이터를 조합하는 이슈가 생길 때 디비를 구축하면 될꺼에요~

@JH27 이 이슈랑 #14 이 이슈에서 혹시 assignee가 바뀌었으면 맞게 직접 수정해서 작업해주세요 :smile_cat:

**Comment by rideddy84** [comment]
@thechunsik @everyone 밖에서 응원할게요, 모두 힘내세요! :smile:

**Comment by hoony-o-1** [comment]
@ace-eddy 지민님은 댓글만으로도 충분히 응원이 되죠!ㅋㅋ 감사해요

**Comment by hoony-o-1** [comment]
https://github.com/codeforseoul/congress-report 이슈, close
