### ISSUE TITLE
개발 서버 준비하기

### ISSUE THREAD

**Issue by mozodev** [codeforseoul/congress-report-web#20]
- digitalocean 512mb swap 설정하면 그런데로 쓸만 아님 걍 1Gb ㅋㅋ
- http://c9.io 구글 클라우드를 사용해서 무료 512mb 우분투 개발용 인스턴스 제공. 팀원과 개발 환경 공유 가능. 

어느 쪽을 선호하시나요? ㅎㅎ

처음 댓글 다는 분의 의견을 존중하겠어요!

**Comment by shindoh** [comment]
2번이요 :)

**Comment by JH27** [comment]
저는 다수결을 따르겠습니다ㅋㅋ 영택님 감사해요!

**Comment by mozodev** [comment]
디지털오션 1GB로 공용 개발 서버를 만들었습니다.
Droplet Name: codeforseoul-dev
IP Address: 128.199.204.73
OS: Ubuntu trusty
참고로 #welfare4u 와 #code4yeouido 두 채널을 위한 계정을 생성했습니다.

비번을 굉장히 흉하게 만들어놔서 가급적 깃헙에 
공개키 등록해놓으신 분들은 키를 추가해드리는걸로~

예를 들면 제 공개키입니다.
https://github.com/mozodev.keys

어쨌든 계정 필요하신 분들은 일단 제게 DM 주세요.

```
codeforseoul-dev
128.199.204.73 
1 GB
30 GB
SGP1
```

**Comment by mozodev** [comment]
앗 그러고 보니 2번이 c9.io 였군요 ㅋㅋㅋㅋㅋㅋ 당연히 서버라고 생각하고 ㅋㅋㅋ 아 정신없다... 
그럼 다음번 밋업에 같이 만들어볼까요? 이 서버는 공용 개발 서버나 스테이징으로 사용해도 되니까요.. ㅋㅋㅋ
