### ISSUE TITLE
특정 선거구를 선택할 때 에러 IndexError: list index out of range

### ISSUE THREAD

**Issue by hoony-o-1** [codeforseoul/congress-report-web#22]
몇 가지 선거구를 선택했을 때 다음 에러가 뜨네요. 어떤 선거구는 잘 되고...

``` bash
 File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/hoony/Projects/congress-report/index.py", line 34, in get_member_idx
    return str(find_member_idx(city_name, local_name, town_name))
  File "/Users/hoony/Projects/congress-report/districtfinder.py", line 41, in find_member_idx
    return find_member_idx_with_district(city_name, find_district_name(city_name, local_name, town_name))
  File "/Users/hoony/Projects/congress-report/districtfinder.py", line 36, in find_member_idx_with_district
    selected_member = list(filter(lambda x: x['district'] == gen_district, assembly_data))[0]
IndexError: list index out of range
```

**Comment by mozodev** [comment]
```
selected_member = list(filter(lambda x: x['district'] == gen_district, assembly_data))[0]
```

요 부분에서 실제로 못 찾아서 그런거네요.. 
포퐁 데이터에서 district 지역을 뽑아보니 저렇네요...

```
districts = [x.get('district') for x in assembly_data]
```

['경남 창원시성산구', '광주 북구갑', '울산 울주군', '전북 남원시순창군', '경북 영양군영덕군봉화군울진군', '서울 서초구을', '비례대표', '제주 제주시갑', '대전 중구', '충북 증평군진천군괴산군음성군', '강원 강릉시', '대구 북구갑', '광주 광산구을', '서울 양천 구갑', '경기 부천시원미구갑', '전북 군산시', '경북 안동시', '비례대표', '강원 원주시갑', '비례대표', '비례대표', '부산 북구강서 구을', '충남 당진시', '광주 광산구갑', '경기 안산시단원구갑', '부산 영도구', '경기 용인시을', '비례대표', '대구 서구', '경기 부 천시소사구', '전남 여수시갑', '전북 전주시덕진구', '경남 창원시진해구', '서울 강서구을', '부산 금정구', '전남 고흥군보성군', '전남 해남군완도군진도군', '경기 포천시연천군', '서울 영등포구갑', '경기 안산시상록구을', '경기 수원시병', '비례대표', '서울 양천구을', '제주 제주시을', '전북 전주시완산구갑', '서울 송파구병', '비례대표', '경남 진주시을', '경북 군위군의성군청송군', '제주 서귀포시', '비례대표', '부산 남구갑', '비례대표', '충남 서산시태안군', '경북 상주시', '서울 강남구을', '강원 춘천시', '전북 고창군부안군', '경기 성남시수정구', '경기 고양시덕양구을', '경남 김해시을', '경북 구미시을', '충남 보령시서천군', '경기 안성시', '서울  광진구갑', '경남 거제시', '비례대표', '경기 고양시일산서구', '비례대표', '서울 서초구갑', '대구 중구남구', '부산 연제구', '서울 동작구을', '부산 부산진구갑', '비례대표', '충북 청주시흥덕구을', '서울 마포구갑', '경기 광주시', '비례대표', '대구 동구갑', '비 례대표', '부산 사하구갑', '인천 부평구갑', '부산 사상구', '비례대표', '경기 의정부시갑', '서울 동대문구을', '비례대표', '비례대 표', '경남 김해시갑', '경기 수원시정', '경기 남양주시을', '인천 남동구갑', '울산 북구', '경남 진주시갑', '충북 보은군옥천군영동 군', '울산 남구을', '경북 포항시남구울릉군', '전북 진안군무주군장수군임실군', '부산 북구강서구갑', '대전 서구을', '대전 서구갑', '인천 중구동구옹진군', '경남 창원시의창구', '충남 공주시', '서울 구로구을', '충남 천안시을', '비례대표', '비례대표', '서울 송파구갑', '광주 동구', '전남 목포시', '비례대표', '광주 서구갑', '서울 중랑구을', '부산 해운대구기장군갑', '비례대표', '비례대표', '경기 광명시갑', '충북 청원군', '경기 안산시단원구을', '비례대표', '대구 북구을', '서울 중랑구갑', '부산 남구을', '경기 화성시갑', '경기 부천시원미구을', '비례대표', '충북 제천시단양군', '비례대표', '경기 의왕시과천시', '비례대표', '서울 영등포구을', '서울 성북구을', '서울 강서구갑', '서울 강동구갑', '경기 성남시중원구', '경남 산청군함양군거창군', '비례대표', '전남 나주시화순군', '인천 계양구갑', '경기 고양시덕양구갑', '서울 강남구갑', '서울 강동구을', '경기 안양시동안구을', '경북 구미시갑', '서울 동대문구 갑', '경기 오산시', '인천 서구강화군을', '서울 노원구병', '경남 창원시마산회원구', '울산 동구', '충남 천안시갑', '비례대표', '경남 사천시남해군하동군', '강원 태백시영월군평창군정선군', '서울 관악구을', '서울 강북구갑', '충북 청주시흥덕구갑', '서울 서대문구갑', '서울 노원구을', '전남 광양시구례군', '경기 평택시갑', '경기 부천시오정구', '부산 서구', '서울 관악구갑', '서울 강북구을', '전북 정읍시', '대구 동구을', '경기 이천시', '서울 성북구갑', '경기 고양시일산동구', '경기 평택시을', '서울 도봉구을', '서울 송 파구을', '부산 수영구', '인천 남동구을', '비례대표', '인천 남구을', '경남 양산시', '대구 달서구을', '경기 구리시', '경기 파주시 갑', '비례대표', '강원 원주시을', '전남 담양군함평군영광군장성군', '경남 통영시고성군', '서울 노원구갑', '비례대표', '충남 아산 시', '서울 금천구', '서울 은평구갑', '경북 포항시북구', '대전 유성구', '비례대표', '전북 전주시완산구을', '경기 안양시동안구갑', '경기 광명시을', '비례대표', '충남 부여군청양군', '경북 고령군성주군칠곡군', '경기 용인시갑', '비례대표', '경기 화성시을', '전 남 무안군신안군', '강원 동해시삼척시', '서울 구로구갑', '충남 논산시계룡시금산군', '비례대표', '대전 동구', '비례대표', '서울 은평구을', '전남 순천시곡성군', '경기 안양시만안구', '충북 충주시', '대구 달성군', '경기 성남시분당구갑', '경남 창원시마산합포구', '부산 동래구', '경기 수원시갑', '울산 남구갑', '경북 김천시', '전북 익산시갑', '경기 군포시', '인천 서구강화군갑', '대구 수성구갑', '경북 문경시예천군', '세종특별자치시', '부산 부산진구을', '경기 하남시', '서울 도봉구갑', '광주 북구을', '비례대표', '광주 남구', '경북 영주시', '비례대표', '서울 동작구갑', '비례대표', '전북 익산시을', '경기 성남시분당구을', '경기 안산시상록구갑', ' 울산 중구', '서울 서대문구을', '강원 속초시고성군양양군', '경기 수원시을', '경기 여주군양평군가평군', '경기 양주시동두천시', '서울 종로구', '경북 경주시', '대전 대덕구', '충북 청주시상당구', '부산 중구동구', '비례대표', '서울 마포구을', '서울 중구', '경북 영천시', '부산 사하구을', '비례대표', '대구 달서구병', '경기 시흥시을', '경남 밀양시창녕군', '경남 의령군함안군합천군', '전남 여수시을', '비례대표', '대구 수성구을', '비례대표', '비례대표', '서울 용산구', '광주 서구을', '경북 경산시청도군', '전북 김제시완 주군', '비례대표', '비례대표', '비례대표', '인천 계양구을', '경기 남양주시갑', '서울 성동구갑', '서울 광진구을', '부산 해운대구 기장군을', '강원 철원군화천군양구군인제군', '비례대표', '경기 용인시병', '비례대표', '경기 시흥시갑', '경기 의정부시을', '충남  홍성군예산군', '인천 부평구을', '비례대표', '서울 성동구을', '인천 남구갑', '비례대표', '대구 달서구갑', '경기 김포시', '강원 홍천군횡성군', '인천 연수구', '비례대표', '전남 장흥군강진군영암군']

또 문제가 
`gen_district = city_name[0:2] + ' ' + district_name` 
요부분 예를 들어 전라남도 목포시 이렇게 선택하면 `전라 목포시 == 전남 목포시`

일단 졸려서 자야겠어요 ㅋㅋㅋㅋ

**Comment by mozodev** [comment]
4 글자일때 0,2를 뽑으면 안되려나요? ㅋㅋㅋㅋㅋ

**Comment by hoony-o-1** [comment]
ㅋㅋㅋ 일단 주무시고 내일 희진님과 함께 얘기해봐요 ㅋㅋㅋㅋㅋ 아 내일 점심먹으로 가요! 내일 뵐게요

**Comment by appetizermonster** [comment]
4글자 지역들하고 세종시 처리할 수 있게 수정했습니다. ㅋㅋ
@a61a870a19c0a3193daa78fb1a17ac0ad3e29f18

**Comment by hoony-o-1** [comment]
오! 수고하셨어요 ! :) 한번 살펴볼게요! @Yeyeon 님과 쌈빡한 디자인을 앞으로 입혀보도록 할게요!ㅋㅋㅋ

**Comment by mozodev** [comment]
땡기고 함 돌려봤는데 잘 되네요! :+1: 
![2015-08-12 10 59 23](https://cloud.githubusercontent.com/assets/1661950/9215219/a19323b6-40e2-11e5-807d-da22e181ae4c.png)

**Comment by hoony-o-1** [comment]
정신이 없어서 이제야 pull을 받아봤어요 ㅋㅋ 확인!! 이제 @Yeyeon 님과 디자인을 입혀보죠!ㅋㅋ
